### ISSUE TITLE
is the idle timer in seconds or mills?

### ISSUE THREAD

**Issue by AUSBird** [joelam789/sharp-network#1]

**Comment by joelam789** [comment]
**in seconds**.

see _SessionGroup.cs_ line#91:   

``` javascript
if (m_IdleTime > 0) Thread.Sleep(m_IdleTime * 1000);
```

sorry for no docs available for now ...

**Comment by joelam789** [comment]
And please note that  **Thread.Sleep(m_IdleTime \* 1000)**  would make the trigger time of the idle event not very exact
